var architects = [
"H.W.Atkinson",
"C.McLay",
"A.H.Conrad",
"T.B.F.Gargett",
"V.T.Curtis",
"C.A.Hamilton",
"L.H.Hailey",
"K.H.Frost",
"W.A.H.Conrad",
"P.R.Gargett",
"J.M.Orange",
"J.D.McPhee",
"F.R.Holmes",
"R.Hawkins",
"G.Cummings",
"W.Duhs",
"K.R.Whiteoad",
"I.D.Charton",
"A.Bligh",
"C.W.Jessup",
"A.Bretnall",
"H.J.Parkinson",
"R.Voller",
"G.Bligh",
"B.Ryan",
"J.Voller",
"K.Langer",
"B.Wilson"
];

var firms = [
"Conrad & Gargett",
"BVN",
"Karl Langer",
"Hayes & Scott",
"Wilson Architects"
];

var clients = [
"Arawa Tavern",
"Bougainville Copper Ltd",
"Carlton & United Breweries Queensland Ltd",
"Christmas Residence",
"Civic & Civic Pty Ltd",
"Cyclone Housing",
"Day Centres",
"Department of the Co-ordinator General and the Queensland Agricultural College Council",
"Glendale System Housing",
"Hamlet Estate Housing",
"Hervey Bay Retirement Village",
"Home Units",
"Inala Youth Club",
"James Hardie Trading Ltd Office and Vehicle Parc",
"Karana Community Centre",
"Lamb Home",
"Mermaid Town Houses",
"MLC Offices",
"Poultry Abattoir ",
"Presbyterian Church of Australia",
"Queensland Agricultural College",
"Runaway Bay Hotel",
"Runaway Town Pty Ltd",
"Sanitarium Health Food Co.",
"Silverton Centre",
"Sports Union of University of Queensland",
"State Government of Queensland",
"Stirling Henry Pty Ltd Warehouse and Workshop",
"Sub-Normal Children's Home",
"Supreme Court Building",
"Toombul Shopping Town",
"Watkins Property and Administration Pty Ltd"
];
